name: bot_web
version: 0.21.0-dev
author: Kevin Moore <kevin@thinkpixellab.com>
description: A collection of (mostly) general libraries to make working with Dart more productive.
homepage: https://github.com/kevmoo/bot_web.dart
documentation: http://kevmoo.github.io/bot_web.dart/
environment:
  sdk: '>=0.8.10+6 <2.0.0'
dependencies:
  bot: '>=0.25.1'
  logging: '>=0.9.0 <0.10.0'
dev_dependencies:
  bot_test: '>=0.1.5'
  browser: '>=0.9.0 <0.10.0'
  hop: '>=0.27.0'
  html5lib: '>=0.9.0 <0.10.0'
  path: '>=0.9.0 <0.10.0'
  unittest: '>=0.9.0 <0.10.0'
